finos/compliant-financial-infrastructure

- README.md
This pull request updates the Cloud Service Certification README to reference project materials on the FINOS Wiki and project materials in the GitHub Wiki as pages are migration from FINOS to GitHub.
> Updated project README to reference project wikis on FINOS and GitHub

- aws/lambda/lambda_template.yml
This PR is to remove the AWS copyright notice from `aws/lambda/lambda_template.yml` to reflect the same template format in `/aws/redshift/redshift_template_public.yml`
```
```
> Remove AWS copyright notice from Lambda and SQS Queue template

- README.md
The contributor copyright notice `Copyright 2019 JPMC` has been removed from the project README in favour of `Copyright 2019 JPMC` that was originally added to the project NOTICE file.
https://github.com/finos/cloud-service-certification/blob/master/NOTICE
This PR is being raised as part of a housekeeping exercise on the repository as the Cloud Service Certification project ready themselves for further contribution.
> Removed copyright from README in favour of NOTICE file

- .github/ISSUE_TEMPLATE/Meeting.md
Add GitHub Issue template for creating and tracking Cloud Service Certification meeting agendas, minutes and attendance using GitHub issues.
> Add GitHub Issue template for Cloud Service Certification meetings

- README.md
This PR adds the following **Service Approval Accelerator** and **Redshift Example** markdown to README.MD.
**Service Approval Accelerator Addition**
```
The [Service Approval Accelerator](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) describes each service contributed to Cloud Service Certification alongside test cases and infrastructure as code.
A single [Service Approval Accelerator](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) document should be contributed with every service contributed to Cloud Service Certifcation. 
_See AWS Redshift example below_.
```
**Redshift Example Addition**
```
The [AWS RedShift Service …
```
> Add Service Accelerator Template and Redshift Example to README

- docs/open-roles/bdd-test-case-development-role.md
- docs/open-roles/cloud-service-certification-documentation-role.md
- docs/open-roles/cloud-service-effort-owner.md
- docs/open-roles/codified-controls-development-role.md
- docs/open-roles/compliance-framework-mapping-role.md
- docs/open-roles/peer-reviewer-role.md
- docs/open-volunteer-roles.md
- docs/project-charter.md
The Cloud Service Certification wiki is currently hosted behind the [CSC GitHub Wiki tab](https://github.com/finos/cloud-service-certification/wiki), which means pull requests cannot be raised in order to add or update wiki markdown content. 
This pull request transfers the markdown content of the CSC Wiki into a `docs` folder that reflects the following structure so the CSC project can take ownership of project content without editorial rights permissions.
```
|__ docs
|__ open-roles
|__ bdd-test-case-development-role.md
|__ cloud-service-certification-documentation-role.md
|__ cloud-service-effort-owner.md
|__ codified-controls-development-role.md
|__ compliance-framework-mapping-role.md
|__ peer-reviewer-role.md
|__ open-volunteer-roles.md
|__ project-charter.md
```
* closes #16
> Transfer markdown content from Cloud Service Certification wiki tab on GitHub into a docs folder in the repo

- .github/workflows/meetings.yml
This should fix the action error on https://github.com/finos/cloud-service-certification/actions/runs/370781622
I followed indications found on https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
Could you please merge this PR and try to re-run the failed action please?
> Replacing deprecated set-env command

- .github/ISSUE_TEMPLATE/Meeting.md
This pull request updates the CSC project meeting WebEx link in `Meeting.md` to make sure the WebEx link presented in GitHub Issue agendas is the same as the [FINOS project calendar](https://calendar.google.com/calendar/u/0/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig@group.calendar.google.com&ctz=America/New_York). 
- update csc webex link to reflect finos calendar 025fa05
- `https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321`
- `https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975`
> Update CSC WebEx Link to Reflect FINOS Project Calendar

- docs/agile-workflow/README.md
This pull request adds the content of https://github.com/finos/cloud-service-certification/issues/106#issuecomment-791403129 to the project repo as `docs/agile-workflow/README.md` and closes #106
```
The Agile Workflow for Cloud Service Certification falls into two main work streams which are overseen by CSC Project Maintainers and fulfilled by the CSC project team and wider FINOS community.
- [Agile Delivery of Prioritised Work Items](#agile)
- [Community Contributions and Pull Requests](#community)
- Cloud Service Certification is an agile project with agreed agile ceremonies and a fixed sprint cadence. Example agile ceremonies include ...
- Regular team stand-ups
- Backlog grooming sessions
- Pre-sprint planning
- End of sprint demos
- Sprint cadence is  **monthly**, as agreed with the …
```
> Evolving CSC Team Roles, Agile Ceremonies and Sprint Cadence

- docs/agile-workflow/README.md
This is a minor update to the [Project Operations Manager](https://github.com/finos/cloud-service-certification/blob/master/docs/open-roles/project-operations-manager.md) role link and Maintainer Team reference following the merge of #99
**From** : `https://github.com/finos/cloud-service-certification/pull/99`
**To** : `https://github.com/finos/cloud-service-certification/blob/master/docs/open-roles/project-operations-manager.md`
**From** : `https://github.com/orgs/finos/teams/cloud-cert-maintainers` _(404 if GitHub profile not part of [FINOS Organisation](https://github.com/orgs/finos/people))_
**To** : `@finos/cloud-cert-maintainers`
> Update Project Operations Manager role link and Maintainer Team reference

- README.md
This PR adds a Slack badge to the Cloud Service Certification project that links to https://finos-lf.slack.com/messages/cloud-service-certification/
```
[<img src="https://img.shields.io/badge/slack-@finos/cloud%20service%20certification-green.svg?logo=slack">](https://finos-lf.slack.com/messages/cloud-service-certification/)
```
[<img src="https://img.shields.io/badge/slack-@finos/cloud%20service%20certification-green.svg?logo=slack">](https://finos-lf.slack.com/messages/cloud-service-certification/)
> Add Slack Badge to Cloud Service Certification

- gcp/gke/gke-terraform-scripts/main.tf
- gcp/gke/gke-terraform-scripts/modules/Bastion_Host/main.tf
- gcp/gke/gke-terraform-scripts/modules/kubernetes/main.tf
- gcp/gke/gke-terraform-scripts/modules/kubernetes/variables.tf
- gcp/gke/gke-terraform-scripts/modules/subnetwork/variables.tf
- gcp/gke/gke-terraform-scripts/variables.tf
`terraform fmt` is the canonical method for formatting Terraform for readability.  I suggest we require the use of this before any PRs are accepted into the project.
> Use terraform fmt for canonical terraform formatting

- README.md
- docs/agile-workflow/README.md
This helps with:
1. Switching master -> main, since those links would otherwise point nowhere.
2. Forks
3. Clones not on GitHub
Links in GitHub README files should in general be relative, see [the
relevant documentation][1].
[1]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes#relative-links-and-image-paths-in-readme-files
> README: Make absolute links to the master branch relative

- README.md
This PR updates the CSC README.md to update repo visitors of the recent branch change from `master` to `main`.
The CSC default branch has been renamed. 
`master` is now named `main`
If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
Closes #119
> Master to Main README Update

- .github/actions/terraform-apply/action.yml
- .github/actions/terraform-destroy/action.yml
- .github/actions/terraform-validate/action.yml
- .github/workflows/aws-eks-verify.yml
- .github/workflows/meetings.yml
- .github/workflows/terraform.yml
- aws/eks/eks-terraform-scripts/kubernetes.tf
Makes use of composable actions to promote code reuse for later workflows per provider/resource.
Includes a filter similar to https://github.com/finos/cloud-service-certification/pull/148 to ensure we only run the workflow whenever relevant files are changed.
Yet to be solved is how to ensure such workflows are run sequentially. Setting `concurrency` is potentially a no-go as it cancels pending pipelines, with no current way to disable that behaviour.
Part of https://github.com/finos/cloud-service-certification/issues/124.
> Add new eks terraform deployment check

- .github/workflows/terraform.yml
Somewhat self-explanatory. While it currently doesn't cost us much, there are cases where we obviously don't need to run the workflow: for example when a PR adds a new text document. As such I've set the patterns we care about for determining whether the terraform formatting checks are run.
> Only run terraform check when we change the relevant files

- .github/workflows/aws-eks-verify.yml
- aws/eks/eks-terraform-scripts/probr-config.yml
Probr tests are NOT expected to pass on the first try here. I have disabled the final `exit 1` (failure) within `Check Probr Validation Result` until the EKS cluster is in a fully compliant state.
> Added probr steps to aws-eks-verify workflow

- README.md
This pull request updates the previous Cloud Service Certification project logo on the project `README.md` with the newly updated Compliant Financial Infrastructure version below.
The following is the new CFI logo that replaced the previous CSC version.
```
```
```
```
> Update Compliant Financial Infrastructure Readme Logo

- .github/ISSUE_TEMPLATE/Meeting.md
This PR removes the now obsolete Cloud Service Certification wiki URL from `.github/ISSUE_TEMPLATE/Meeting.md`.
```
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project
```
> Remove Wiki URL from Meeting Template

- .github/workflows/aws-eks-verify.yml
- .github/workflows/terraform.yml
- aws/eks/eks-terraform-scripts/eks-cluster.tf
- aws/eks/eks-terraform-scripts/versions.tf
At some point we'll want to update our dependencies to the latest versions and modify our terraform to work with them, but for now i've locked them to known working versions.
- Fix invalid yaml - due to using multiline syntax with only a single line
- Lock terraform version to 1.0.x
- Lock eks' terraform aws versions.  Important one is `hashicorp/aws` needs to be <= `3.63.0`
- Lock eks' terraform module version, as 18.x needs the above to be `>3.64.0`
- Probr's volume setup wasn't working correctly as it needed absolute paths
> Fixes for CI failures

- .github/workflows/aws-eks-verify.yml
As v0.1.2 was cut with an error still remaining in the AWS handling, I've made changes and created a RC that addresses that issue.
> Updated to use Probr container v0.1.3-rc

- accelerators/kubernetes/ocp/expanded-sec-details.adoc
- accelerators/kubernetes/ocp/sat_rh_ocp.adoc
Updates to the OpenShift service accelerators documents to reflect release of OpenShift 4.10. No changes to policies, changes to documentation links. 
[sat_rh_ocp.adoc](https://github.com/finos/compliant-financial-infrastructure/blob/dev/accelerators/kubernetes/ocp/sat_rh_ocp.adoc)
https://github.com/finos/compliant-financial-infrastructure/blob/dev/accelerators/kubernetes/ocp/expanded-sec-details.adoc
> OpenShift Service Accelerators documentation updates 

- docs/CONTRIBUTING.md
> The project MUST use at least one automated test suite that is publicly released as FLOSS (this test suite may be maintained as a separate FLOSS project). The project MUST clearly show or document how to run the test suite(s) (e.g., via a continuous integration (CI) script or via documentation in files such as BUILD.md, README.md, or CONTRIBUTING.md). [test]
> OpenSSF automated test documentation

- README.md
Reverts finos/compliant-financial-infrastructure#354. Sorry @eddie-knight reverting changes to the [repo](https://github.com/finos/branding/pull/33) as it was causing issues in a couple places. Thanks for the heads up and apologies for the inconvenience!
> Revert "Logo fix"
