finos/compliant-financial-infrastructure

README.md

Adds a Cloud Service Certification kanban link to the project README.MD

Add kanban link to README.MD

---

aws/dynamodb/ServiceApprovalAccelerator-DynamoDB.md

Service Approval Accelerator DynamoDB converted from DOCX to MD and added to project

Service Approval Accelerator DynamoDB MD File Added

---

.github/meetings.yml

Enabling FINOS GitHub Action for managing Cloud Service Certification meetings and minutes.

Create FINOS GitHub Action for managing Cloud Service Certification meetings

---

.github/ISSUE_TEMPLATE/Meeting.md

Add space between emoji and text in GitHub Issue meeting template.

Add space between emoji and text in GitHub Issue meeting template

---

.github/workflows/meetings.yml

action posts comment to report unknown participants

Action posts comment to report unknown participants

---

templates/ServiceApprovalAcceleratorTemplate.md

As discussed in our previous meeting, I am updating the table in the template to include more detail and a breakdown of categories. I have also removed the RedShift specific examples and added prompts as to the information that should be included in each section - please feel free to amend these/add extra detail to help users understand and use the template.

Updating template table to include new categories and extra detail

---

.github/ISSUE_TEMPLATE/Meeting.md

Following changes made to `.github/ISSUE_TEMPLATE/Meeting.md`
* Changed meeting title to `Agenda` from `Minutes`
* Added `3pm BST` to meeting time
* Added minutes review filter to agenda
* Corrected repo URL by removing `fdx` path

Changed meeting title, added 3pm BST, added minutes review and corrected repo link

---

docs/your-questions-answered.md

The question **How does Cloud Service Certification maintain the security of the environment and the protection of the environment for open source consumers?** was asked by the CSC community in issue #18
This pull request add a `Add Your Questions Answered` page to the CSC wiki so relevant answers can be transferred from GitHub Issues and displayed on the wiki.
closes #18

Add Your Questions Answered page to the CSC wiki

---

gcp/gke/gke-terraform-scripts/README.txt
gcp/gke/gke-terraform-scripts/main.tf
gcp/gke/gke-terraform-scripts/modules/Bastion_Host/main.tf
gcp/gke/gke-terraform-scripts/modules/Bastion_Host/variables.tf
gcp/gke/gke-terraform-scripts/modules/kubernetes/main.tf
gcp/gke/gke-terraform-scripts/modules/kubernetes/variables.tf
gcp/gke/gke-terraform-scripts/modules/subnetwork/main.tf
gcp/gke/gke-terraform-scripts/modules/subnetwork/variables.tf
gcp/gke/gke-terraform-scripts/variables.tf

Hi Finos team,
Here is some code contribution to the gcp/gke module of clous-service-certification. 
It is a terraform script for the deployment of a secure GKE infrastructure environment on GCP.
Note: I will modify the README text doc to markdown format soon

Pull request for GKE TF scripts

---

.github/CONTRIBUTING.md

Following the call today, I'm hoping this PR will get the conversation started regarding a standardized organization.
https://github.com/eddie-knight/cloud-service-certification/blob/citihub/proposed-reorganization/docs/directory-structure.md

Adding structure expectations to CONTRIBUTING.md

---

aws/eks/eks-terraform-scripts/README.md
aws/eks/eks-terraform-scripts/eks-cluster.tf
aws/eks/eks-terraform-scripts/variables.tf

- Declare and set variables to handle worker groups details.
- Document the supported versions in the Terraform modules.

AWS EKS Review, Feedback and Update

---

.github/ISSUE_TEMPLATE/Meeting.md
LICENSE.spdx
README.md
docs/open-roles/README.md
docs/open-roles/cloud-service-certification-project-maintainer.md
docs/open-roles/project-operations-manager.md
docs/project-charter.md
docs/your-questions-answered.md

This PR updates internal project documentation linking from `cloud-service-certification` to `compliant-financial-infrastructure`.

Update internal documentation linking from `cloud-service-certification` to `compliant-financial-infrastructure`

---

.github/ISSUE_TEMPLATE/Meeting.md
README.md

This PR changes the CFI meeting cadence to Friday @ 10am ET / 3pm UK as a result of the following project poll ...
- https://github.com/finos/compliant-financial-infrastructure/discussions/154#discussioncomment-1509589
- 88da9c9c1bf4bddd9033b0a96fd8916c75df5e28
```
Friday DD MMM yyyy - 10am ET / 3pm UK
```

Update Friday Meeting Cadence

---

.github/workflows/aws-eks-verify.yml

Run CI to test #189 is working correctly.

Validation run for #189

---

README.md

- Added feature matrix
- Removed "Important Notice" as a fair amount of time has passed since we changed repos (and it automatically redirects anyhow)
- Added IBM Cloud to the list of cloud providers
-  Adjusted "Approach and Solution" to include explicit details about the project output

Adjusted main README to include feature-matrix

---

README.md

Added a new section in the primary readme to answer this commonly asked question

Updated our definition of 'compliant' and how it is achieved in CFI

---

accelerators/kubernetes/eks/tf_cdmc_aws_eks/eks-cluster.tf

Changed EKS terraform to use k8s v1.23

---

accelerators/kubernetes/eks/tf_cdmc_aws_eks/eks-cluster.tf
accelerators/kubernetes/eks/tf_cdmc_aws_eks/security-groups.tf
accelerators/kubernetes/eks/tf_cdmc_aws_eks/versions.tf
accelerators/kubernetes/eks/tf_cdmc_aws_eks/vpc.tf

- Correct naming convention.
- Updating versions.
- Removing unnecessary options/parameters.

Updating Terraform files.

---

accelerators/kubernetes/eks/tf_cdmc_aws_eks/eks-cluster.tf
accelerators/kubernetes/eks/tf_cdmc_aws_eks/versions.tf
accelerators/kubernetes/eks/tf_cdmc_aws_eks/vpc.tf

Stabilised versions update.

---

.github/ISSUE_TEMPLATE/Meeting.md
docs/open-roles/cloud-service-certification-project-maintainer.md
docs/open-roles/project-operations-manager.md

This PR replaces deprecated links in the readme and github issues template files

replace broken links

---

docs/terraform-module-best-practices.md

Add Terraform initial best practices document.

Add TF BPs

---

.github/ISSUE_TEMPLATE/Meeting.md

This PR changes the main CFI project meeting GitHub Issue template title to `Monthly Compliant Financial Infrastructure Meeting Agenda`.

Update CFI Project Meeting Template Title

---

README.md
docs/CONTRIBUTING.md

Removed large swaths of content from the README. We may want to come back here to restore some of this content in individual WG documentation, as needed.
The main focus of the readme is now on our WGs, including the objectives and approach.
Open to criticism and suggestions here :+1:

Adjusted README to highlight working groups

---

accelerators/kubernetes/eks/saa_aws_eks.md
templates/ServiceApprovalAcceleratorTemplate.md

Hi,
Creating pull request as discussed in the Policy WG meeting today.
Thanks.
Abdullah Garcia

SAA AWS EKS + SAA Template Update

---

README.md

Recommend viewing this PR in markdown preview mode

Add warning to README.md

---

LICENSE
LICENSE.spdx

Update license to community commons

Adds community commons license
